//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.Cliente_Articulo = new HashSet<Cliente_Articulo>();
            this.Historial_Transaccion = new HashSet<Historial_Transaccion>();
        }
    
        public int ID { get; set; }
        public int ID_Consecutivo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int ID_Precio { get; set; }
        public string Imagen { get; set; }
    
        public virtual Consecutivo Consecutivo { get; set; }
        public virtual Precio Precio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente_Articulo> Cliente_Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial_Transaccion> Historial_Transaccion { get; set; }
    }
}
