//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public string ID_Consecutivo { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Hora { get; set; }
        public int Codigo_registro { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public string Detalle { get; set; }
    
        public virtual Consecutivo_Objeto Consecutivo_Objeto { get; set; }
    }
}
