//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_Habitacion
    {
        public int ID { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_Habitacion { get; set; }
        public System.DateTime Fecha_Hora_Entrada { get; set; }
        public Nullable<System.DateTime> Fecha_Hora_Salida { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
