//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Compra_Habitacion = new HashSet<Compra_Habitacion>();
        }
    
        public int ID_Compra { get; set; }
        public string ID_Cliente { get; set; }
        public string Mascotas { get; set; }
        public string ID_Cod_Promo { get; set; }
        public System.DateTime Fecha_Hora_Entrada { get; set; }
        public System.DateTime Fecha_Hora_Salida { get; set; }
        public Nullable<int> Num_Habitaciones { get; set; }
        public Nullable<decimal> Precio_Total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Codigo_Descuento Codigo_Descuento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_Habitacion> Compra_Habitacion { get; set; }
    }
}
