//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Habitacion
    {
        public int ID_Comp_Habit { get; set; }
        public int ID_Compra { get; set; }
        public string ID_Habitacion { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
