//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutivo_Objeto
    {
        public string ID_ConsecutivoObjeto { get; set; }
        public int Codigo_Consecutivo { get; set; }
        public Nullable<int> Ultimo_Digito { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Bitacora Bitacora { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Consecutivo Consecutivo { get; set; }
        public virtual Habitacion Habitacion { get; set; }
        public virtual Precio Precio { get; set; }
    }
}
