//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consecutivo()
        {
            this.Consecutivo_Objeto = new HashSet<Consecutivo_Objeto>();
        }
    
        public int Codigo { get; set; }
        public string ID_Consecutivo { get; set; }
        public string Descripcion { get; set; }
        public string Prefijo { get; set; }
        public Nullable<int> Rango_inicial { get; set; }
        public Nullable<int> Rango_final { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consecutivo_Objeto> Consecutivo_Objeto { get; set; }
    }
}
