//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitaciones()
        {
            this.Cliente_Habitaciones = new HashSet<Cliente_Habitaciones>();
            this.Historial_Transacciones = new HashSet<Historial_Transacciones>();
        }
    
        public int ID { get; set; }
        public int ID_Consecutivo { get; set; }
        public string Nombre { get; set; }
        public int Numero { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public string Disponibilidad { get; set; }
        public int ID_Precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente_Habitaciones> Cliente_Habitaciones { get; set; }
        public virtual Consecutivo Consecutivo { get; set; }
        public virtual Precios Precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial_Transacciones> Historial_Transacciones { get; set; }
    }
}
