//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Transaccion
    {
        public int ID { get; set; }
        public string ID_Cliente { get; set; }
        public int Metodo_pago { get; set; }
        public int Monto { get; set; }
        public string ID_Habitacion { get; set; }
        public Nullable<int> ID_Articulo { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
