//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Cliente_Articulo> Cliente_Articulo { get; set; }
        public virtual DbSet<Codigo_Descuento> Codigo_Descuento { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Compra_Habitacion> Compra_Habitacion { get; set; }
        public virtual DbSet<Consecutivo> Consecutivo { get; set; }
        public virtual DbSet<Consecutivo_Objeto> Consecutivo_Objeto { get; set; }
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Historial_Transaccion> Historial_Transaccion { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<Reservacion> Reservacion { get; set; }
        public virtual DbSet<Reservacion_habitacion> Reservacion_habitacion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario_Admin> Usuario_Admin { get; set; }
    
        public virtual ObjectResult<string> BuscarPrefijo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BuscarPrefijo", codigoParameter);
        }
    
        public virtual int ChangePassword(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangePassword", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<ComprasCliente_Result> ComprasCliente(string iD_Cliente)
        {
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComprasCliente_Result>("ComprasCliente", iD_ClienteParameter);
        }
    
        public virtual ObjectResult<consulta_NombreUsuario_Result> consulta_NombreUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consulta_NombreUsuario_Result>("consulta_NombreUsuario");
        }
    
        public virtual ObjectResult<string> HabitacionCompra(Nullable<int> iD_Compra)
        {
            var iD_CompraParameter = iD_Compra.HasValue ?
                new ObjectParameter("ID_Compra", iD_Compra) :
                new ObjectParameter("ID_Compra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("HabitacionCompra", iD_CompraParameter);
        }
    
        public virtual ObjectResult<InfoHabitacion_Result> InfoHabitacion(string iD_Habitacion)
        {
            var iD_HabitacionParameter = iD_Habitacion != null ?
                new ObjectParameter("ID_Habitacion", iD_Habitacion) :
                new ObjectParameter("ID_Habitacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InfoHabitacion_Result>("InfoHabitacion", iD_HabitacionParameter);
        }
    
        public virtual int insertarConsecutivoObjeto(string iD_ConsecutivoObjeto, Nullable<int> codigo_Consecutivo, Nullable<int> ultimo_Digito)
        {
            var iD_ConsecutivoObjetoParameter = iD_ConsecutivoObjeto != null ?
                new ObjectParameter("ID_ConsecutivoObjeto", iD_ConsecutivoObjeto) :
                new ObjectParameter("ID_ConsecutivoObjeto", typeof(string));
    
            var codigo_ConsecutivoParameter = codigo_Consecutivo.HasValue ?
                new ObjectParameter("Codigo_Consecutivo", codigo_Consecutivo) :
                new ObjectParameter("Codigo_Consecutivo", typeof(int));
    
            var ultimo_DigitoParameter = ultimo_Digito.HasValue ?
                new ObjectParameter("Ultimo_Digito", ultimo_Digito) :
                new ObjectParameter("Ultimo_Digito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertarConsecutivoObjeto", iD_ConsecutivoObjetoParameter, codigo_ConsecutivoParameter, ultimo_DigitoParameter);
        }
    
        public virtual ObjectResult<ObtenertRoles_Result> ObtenertRoles(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenertRoles_Result>("ObtenertRoles", iDParameter);
        }
    
        public virtual ObjectResult<ReservaCliente_Result> ReservaCliente(string iD_Cliente)
        {
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReservaCliente_Result>("ReservaCliente", iD_ClienteParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> ultimo_consecutivo(string prefijo)
        {
            var prefijoParameter = prefijo != null ?
                new ObjectParameter("Prefijo", prefijo) :
                new ObjectParameter("Prefijo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ultimo_consecutivo", prefijoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UltimoNumeroConsecutivo(string iD_Consecutivo)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UltimoNumeroConsecutivo", iD_ConsecutivoParameter);
        }
    
        public virtual int usp_CheckLogin(string username, string password, Nullable<int> result)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var resultParameter = result.HasValue ?
                new ObjectParameter("Result", result) :
                new ObjectParameter("Result", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CheckLogin", usernameParameter, passwordParameter, resultParameter);
        }
    
        public virtual ObjectResult<usp_consulta_actividades_Result> usp_consulta_actividades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consulta_actividades_Result>("usp_consulta_actividades");
        }
    
        public virtual int usp_consulta_articulos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_consulta_articulos");
        }
    
        public virtual ObjectResult<usp_consulta_bitacora_Result> usp_consulta_bitacora()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consulta_bitacora_Result>("usp_consulta_bitacora");
        }
    
        public virtual ObjectResult<usp_consulta_cliente_articulos_Result> usp_consulta_cliente_articulos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consulta_cliente_articulos_Result>("usp_consulta_cliente_articulos");
        }
    
        public virtual int usp_consulta_cliente_habitaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_consulta_cliente_habitaciones");
        }
    
        public virtual ObjectResult<usp_consulta_clientes_Result> usp_consulta_clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consulta_clientes_Result>("usp_consulta_clientes");
        }
    
        public virtual int usp_consulta_codigos_descuento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_consulta_codigos_descuento");
        }
    
        public virtual ObjectResult<usp_consulta_consecutivos_Result> usp_consulta_consecutivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consulta_consecutivos_Result>("usp_consulta_consecutivos");
        }
    
        public virtual ObjectResult<usp_consulta_errores_Result> usp_consulta_errores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consulta_errores_Result>("usp_consulta_errores");
        }
    
        public virtual ObjectResult<usp_consulta_habitaciones_Result> usp_consulta_habitaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consulta_habitaciones_Result>("usp_consulta_habitaciones");
        }
    
        public virtual int usp_consulta_historial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_consulta_historial");
        }
    
        public virtual ObjectResult<usp_consulta_precios_Result> usp_consulta_precios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consulta_precios_Result>("usp_consulta_precios");
        }
    
        public virtual int usp_consulta_reservaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_consulta_reservaciones");
        }
    
        public virtual int usp_elimina_actividad(string iD_Consecutivo)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_elimina_actividad", iD_ConsecutivoParameter);
        }
    
        public virtual int usp_elimina_ConsecutivoObjeto(string iD_Consecutivo)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_elimina_ConsecutivoObjeto", iD_ConsecutivoParameter);
        }
    
        public virtual int usp_info_actividades(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_info_actividades", iDParameter);
        }
    
        public virtual ObjectResult<usp_info_articulos_Result> usp_info_articulos(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_info_articulos_Result>("usp_info_articulos", iDParameter);
        }
    
        public virtual int usp_info_bitacora(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_info_bitacora", iDParameter);
        }
    
        public virtual ObjectResult<usp_info_cliente_articulos_Result> usp_info_cliente_articulos(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_info_cliente_articulos_Result>("usp_info_cliente_articulos", iDParameter);
        }
    
        public virtual int usp_info_cliente_habitaciones(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_info_cliente_habitaciones", iDParameter);
        }
    
        public virtual int usp_info_clientes(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_info_clientes", iDParameter);
        }
    
        public virtual int usp_info_codigos_descuento(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_info_codigos_descuento", codigoParameter);
        }
    
        public virtual ObjectResult<string> usp_info_consecutivo(Nullable<int> descripcion)
        {
            var descripcionParameter = descripcion.HasValue ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_info_consecutivo", descripcionParameter);
        }
    
        public virtual ObjectResult<string> usp_info_consecutivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_info_consecutivos");
        }
    
        public virtual int usp_info_errores(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_info_errores", iDParameter);
        }
    
        public virtual int usp_info_historial(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_info_historial", iDParameter);
        }
    
        public virtual int usp_info_precio(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_info_precio", iDParameter);
        }
    
        public virtual int usp_info_reservacion(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_info_reservacion", iDParameter);
        }
    
        public virtual int usp_inserta_actividad(string iD_Consecutivo, string nombre, string descripcion, string imagen)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_actividad", iD_ConsecutivoParameter, nombreParameter, descripcionParameter, imagenParameter);
        }
    
        public virtual int usp_inserta_articulo(Nullable<int> iD_Consecutivo, string nombre, string descripcion, Nullable<int> iD_Precio, string imagen)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iD_PrecioParameter = iD_Precio.HasValue ?
                new ObjectParameter("ID_Precio", iD_Precio) :
                new ObjectParameter("ID_Precio", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_articulo", iD_ConsecutivoParameter, nombreParameter, descripcionParameter, iD_PrecioParameter, imagenParameter);
        }
    
        public virtual int usp_inserta_bitacora(Nullable<int> iD_Consecutivo, string usuario, Nullable<int> codigo_registro, string tipo, string descripcion, string detalle)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var codigo_registroParameter = codigo_registro.HasValue ?
                new ObjectParameter("Codigo_registro", codigo_registro) :
                new ObjectParameter("Codigo_registro", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_bitacora", iD_ConsecutivoParameter, usuarioParameter, codigo_registroParameter, tipoParameter, descripcionParameter, detalleParameter);
        }
    
        public virtual int usp_inserta_cliente(Nullable<int> iD_Consecutivo, string nombre, Nullable<int> dias_Visita, string activo)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var dias_VisitaParameter = dias_Visita.HasValue ?
                new ObjectParameter("Dias_Visita", dias_Visita) :
                new ObjectParameter("Dias_Visita", typeof(int));
    
            var activoParameter = activo != null ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_cliente", iD_ConsecutivoParameter, nombreParameter, dias_VisitaParameter, activoParameter);
        }
    
        public virtual int usp_inserta_cliente_articulo(Nullable<int> iD_Cliente, Nullable<int> iD_Articulo)
        {
            var iD_ClienteParameter = iD_Cliente.HasValue ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(int));
    
            var iD_ArticuloParameter = iD_Articulo.HasValue ?
                new ObjectParameter("ID_Articulo", iD_Articulo) :
                new ObjectParameter("ID_Articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_cliente_articulo", iD_ClienteParameter, iD_ArticuloParameter);
        }
    
        public virtual int usp_inserta_cliente_habitacion(Nullable<int> iD_Cliente, Nullable<int> iD_Habitacion)
        {
            var iD_ClienteParameter = iD_Cliente.HasValue ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(int));
    
            var iD_HabitacionParameter = iD_Habitacion.HasValue ?
                new ObjectParameter("ID_Habitacion", iD_Habitacion) :
                new ObjectParameter("ID_Habitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_cliente_habitacion", iD_ClienteParameter, iD_HabitacionParameter);
        }
    
        public virtual int usp_inserta_codigo_descuento(Nullable<int> iD_Consecutivo, Nullable<int> iD_Cliente)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente.HasValue ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_codigo_descuento", iD_ConsecutivoParameter, iD_ClienteParameter);
        }
    
        public virtual int usp_inserta_consecutivo(Nullable<int> iD_Consecutivo, string descripcion, string prefijo, Nullable<int> rango_inicial, Nullable<int> rango_final)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var prefijoParameter = prefijo != null ?
                new ObjectParameter("Prefijo", prefijo) :
                new ObjectParameter("Prefijo", typeof(string));
    
            var rango_inicialParameter = rango_inicial.HasValue ?
                new ObjectParameter("Rango_inicial", rango_inicial) :
                new ObjectParameter("Rango_inicial", typeof(int));
    
            var rango_finalParameter = rango_final.HasValue ?
                new ObjectParameter("Rango_final", rango_final) :
                new ObjectParameter("Rango_final", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_consecutivo", iD_ConsecutivoParameter, descripcionParameter, prefijoParameter, rango_inicialParameter, rango_finalParameter);
        }
    
        public virtual int usp_inserta_error(string descripcion, Nullable<int> numero)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_error", descripcionParameter, numeroParameter);
        }
    
        public virtual int usp_inserta_habitacion(string iD_Consecutivo, string nombre, Nullable<int> numero, string descripcion, string imagen, string disponibilidad, string iD_Precio)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            var disponibilidadParameter = disponibilidad != null ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(string));
    
            var iD_PrecioParameter = iD_Precio != null ?
                new ObjectParameter("ID_Precio", iD_Precio) :
                new ObjectParameter("ID_Precio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_habitacion", iD_ConsecutivoParameter, nombreParameter, numeroParameter, descripcionParameter, imagenParameter, disponibilidadParameter, iD_PrecioParameter);
        }
    
        public virtual int usp_inserta_historial(Nullable<int> iD_Consecutivo, Nullable<int> iD_Cliente, Nullable<int> metodo_pago, Nullable<int> monto, Nullable<int> iD_Habitacion, Nullable<int> iD_Articulo)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente.HasValue ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(int));
    
            var metodo_pagoParameter = metodo_pago.HasValue ?
                new ObjectParameter("Metodo_pago", metodo_pago) :
                new ObjectParameter("Metodo_pago", typeof(int));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(int));
    
            var iD_HabitacionParameter = iD_Habitacion.HasValue ?
                new ObjectParameter("ID_Habitacion", iD_Habitacion) :
                new ObjectParameter("ID_Habitacion", typeof(int));
    
            var iD_ArticuloParameter = iD_Articulo.HasValue ?
                new ObjectParameter("ID_Articulo", iD_Articulo) :
                new ObjectParameter("ID_Articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_historial", iD_ConsecutivoParameter, iD_ClienteParameter, metodo_pagoParameter, montoParameter, iD_HabitacionParameter, iD_ArticuloParameter);
        }
    
        public virtual int usp_inserta_precio(string iD_Consecutivo, string tipo, Nullable<double> precio)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_precio", iD_ConsecutivoParameter, tipoParameter, precioParameter);
        }
    
        public virtual int usp_inserta_reservacion(Nullable<int> iD_Consecutivo, Nullable<int> iD_Cliente, Nullable<int> iD_Actividad, Nullable<int> cantidad_Acompañantes, Nullable<int> cantidad_Habitaciones, Nullable<int> booking_id)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente.HasValue ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(int));
    
            var iD_ActividadParameter = iD_Actividad.HasValue ?
                new ObjectParameter("ID_Actividad", iD_Actividad) :
                new ObjectParameter("ID_Actividad", typeof(int));
    
            var cantidad_AcompañantesParameter = cantidad_Acompañantes.HasValue ?
                new ObjectParameter("Cantidad_Acompañantes", cantidad_Acompañantes) :
                new ObjectParameter("Cantidad_Acompañantes", typeof(int));
    
            var cantidad_HabitacionesParameter = cantidad_Habitaciones.HasValue ?
                new ObjectParameter("Cantidad_Habitaciones", cantidad_Habitaciones) :
                new ObjectParameter("Cantidad_Habitaciones", typeof(int));
    
            var booking_idParameter = booking_id.HasValue ?
                new ObjectParameter("Booking_id", booking_id) :
                new ObjectParameter("Booking_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_inserta_reservacion", iD_ConsecutivoParameter, iD_ClienteParameter, iD_ActividadParameter, cantidad_AcompañantesParameter, cantidad_HabitacionesParameter, booking_idParameter);
        }
    
        public virtual int usp_modifica_actividad(string iD_Consecutivo, string nombre, string descripcion, string imagen)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_modifica_actividad", iD_ConsecutivoParameter, nombreParameter, descripcionParameter, imagenParameter);
        }
    
        public virtual int usp_modifica_articulo(Nullable<int> iD, Nullable<int> iD_Consecutivo, string nombre, string descripcion, Nullable<int> iD_Precio, string imagen)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iD_PrecioParameter = iD_Precio.HasValue ?
                new ObjectParameter("ID_Precio", iD_Precio) :
                new ObjectParameter("ID_Precio", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_modifica_articulo", iDParameter, iD_ConsecutivoParameter, nombreParameter, descripcionParameter, iD_PrecioParameter, imagenParameter);
        }
    
        public virtual int usp_modifica_cliente(Nullable<int> iD, Nullable<int> iD_Consecutivo, string nombre, Nullable<int> dias_Visita, string activo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var dias_VisitaParameter = dias_Visita.HasValue ?
                new ObjectParameter("Dias_Visita", dias_Visita) :
                new ObjectParameter("Dias_Visita", typeof(int));
    
            var activoParameter = activo != null ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_modifica_cliente", iDParameter, iD_ConsecutivoParameter, nombreParameter, dias_VisitaParameter, activoParameter);
        }
    
        public virtual int usp_modifica_cliente_habitacion(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_modifica_cliente_habitacion", iDParameter);
        }
    
        public virtual int usp_modifica_consecutivo(Nullable<int> codigo, string iD_Consecutivo, string descripcion, string prefijo, Nullable<int> rango_inicial, Nullable<int> rango_final)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var prefijoParameter = prefijo != null ?
                new ObjectParameter("Prefijo", prefijo) :
                new ObjectParameter("Prefijo", typeof(string));
    
            var rango_inicialParameter = rango_inicial.HasValue ?
                new ObjectParameter("Rango_inicial", rango_inicial) :
                new ObjectParameter("Rango_inicial", typeof(int));
    
            var rango_finalParameter = rango_final.HasValue ?
                new ObjectParameter("Rango_final", rango_final) :
                new ObjectParameter("Rango_final", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_modifica_consecutivo", codigoParameter, iD_ConsecutivoParameter, descripcionParameter, prefijoParameter, rango_inicialParameter, rango_finalParameter);
        }
    
        public virtual int usp_modifica_habitacion(string iD_Consecutivo, string nombre, Nullable<int> numero, string descripcion, string imagen, string disponibilidad, string iD_Precio)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            var disponibilidadParameter = disponibilidad != null ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(string));
    
            var iD_PrecioParameter = iD_Precio != null ?
                new ObjectParameter("ID_Precio", iD_Precio) :
                new ObjectParameter("ID_Precio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_modifica_habitacion", iD_ConsecutivoParameter, nombreParameter, numeroParameter, descripcionParameter, imagenParameter, disponibilidadParameter, iD_PrecioParameter);
        }
    
        public virtual int usp_modifica_historial(Nullable<int> iD, Nullable<int> iD_Consecutivo, Nullable<int> iD_Cliente, Nullable<int> metodo_pago, Nullable<int> monto, Nullable<int> iD_Habitacion, Nullable<int> iD_Articulo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente.HasValue ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(int));
    
            var metodo_pagoParameter = metodo_pago.HasValue ?
                new ObjectParameter("Metodo_pago", metodo_pago) :
                new ObjectParameter("Metodo_pago", typeof(int));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(int));
    
            var iD_HabitacionParameter = iD_Habitacion.HasValue ?
                new ObjectParameter("ID_Habitacion", iD_Habitacion) :
                new ObjectParameter("ID_Habitacion", typeof(int));
    
            var iD_ArticuloParameter = iD_Articulo.HasValue ?
                new ObjectParameter("ID_Articulo", iD_Articulo) :
                new ObjectParameter("ID_Articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_modifica_historial", iDParameter, iD_ConsecutivoParameter, iD_ClienteParameter, metodo_pagoParameter, montoParameter, iD_HabitacionParameter, iD_ArticuloParameter);
        }
    
        public virtual int usp_modifica_precio(string iD_Consecutivo, string tipo, Nullable<double> precio)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo != null ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_modifica_precio", iD_ConsecutivoParameter, tipoParameter, precioParameter);
        }
    
        public virtual int usp_modifica_reservacion(Nullable<int> iD, Nullable<int> iD_Consecutivo, Nullable<int> iD_Cliente, Nullable<int> iD_Actividad, Nullable<int> cantidad_Acompañantes, Nullable<int> cantidad_Habitaciones, Nullable<int> booking_id)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente.HasValue ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(int));
    
            var iD_ActividadParameter = iD_Actividad.HasValue ?
                new ObjectParameter("ID_Actividad", iD_Actividad) :
                new ObjectParameter("ID_Actividad", typeof(int));
    
            var cantidad_AcompañantesParameter = cantidad_Acompañantes.HasValue ?
                new ObjectParameter("Cantidad_Acompañantes", cantidad_Acompañantes) :
                new ObjectParameter("Cantidad_Acompañantes", typeof(int));
    
            var cantidad_HabitacionesParameter = cantidad_Habitaciones.HasValue ?
                new ObjectParameter("Cantidad_Habitaciones", cantidad_Habitaciones) :
                new ObjectParameter("Cantidad_Habitaciones", typeof(int));
    
            var booking_idParameter = booking_id.HasValue ?
                new ObjectParameter("Booking_id", booking_id) :
                new ObjectParameter("Booking_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_modifica_reservacion", iDParameter, iD_ConsecutivoParameter, iD_ClienteParameter, iD_ActividadParameter, cantidad_AcompañantesParameter, cantidad_HabitacionesParameter, booking_idParameter);
        }
    }
}
