//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<Articulos> Articulos { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Cliente_Articulos> Cliente_Articulos { get; set; }
        public virtual DbSet<Cliente_Habitaciones> Cliente_Habitaciones { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Codigos_Descuento> Codigos_Descuento { get; set; }
        public virtual DbSet<Consecutivo> Consecutivo { get; set; }
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<Habitaciones> Habitaciones { get; set; }
        public virtual DbSet<Historial_Transacciones> Historial_Transacciones { get; set; }
        public virtual DbSet<Precios> Precios { get; set; }
        public virtual DbSet<Reservacion_habitaciones> Reservacion_habitaciones { get; set; }
        public virtual DbSet<Usuario_Admin> Usuario_Admin { get; set; }
    }
}
