//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion_habitaciones
    {
        public int ID { get; set; }
        public int ID_Consecutivo { get; set; }
        public int ID_Cliente { get; set; }
        public Nullable<int> ID_Actividad { get; set; }
        public Nullable<int> Cantidad_Acompañantes { get; set; }
        public int Cantidad_Habitaciones { get; set; }
        public int Booking_ID { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Consecutivo Consecutivo { get; set; }
    }
}
