//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Admin
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public int Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<int> ID_Consecutivo { get; set; }
        public string Administrador { get; set; }
        public string Seguridad { get; set; }
        public string Consecutico { get; set; }
        public string Mantenimiento { get; set; }
        public string Consulta { get; set; }
    
        public virtual Consecutivo Consecutivo { get; set; }
    }
}
